config/routes.rb
Rails.application.routes.draw do
  resources :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  get "hashtags" => "hashtag#hashtags"
  get "hashtag/:name" => "hashtag#hashtagposts", :as => 'hashtag_post'
  get "users" => "user#users"
  get "/user/:id" => "user#userposts", :as => 'user_post'
  get "/auth/facebook/callback" => "sessions#create"
  delete "/signout" => "sessions#destroy", :as => :signout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
    def self.create_with_omniauth(auth)
        create! do |user|
          user.uid = auth["uid"]
          user.name = auth["info"]["name"]
          user.photo_url = auth["info"]["image"] 
        end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/hashtag_controller.rb
class HashtagController < ApplicationController
    def hashtags
        @hashtags = Hashtag.all.distinct
        @hashtags_count = Hashtag.group(:name).count(:post_id)
        render template: "pages/hashtags_all"
    end

    def hashtagposts
        @hashtag_posts = Array.new
        @hashtag = Hashtag.select(:post_id).where(name: params[:name]).find_all
        @hashtag.each do |h|
            @hashtag_posts.push(Post.find(h.post_id))
        end
        render template: "pages/hashtags_posts"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @posts = Post.all.order("created_at DESC")
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.create! params.require(:post).permit(:title, :body, :hashtags)
        @post.uid = current_user.uid
        @post.save
        hst = params[:post][:hashtags].gsub(/\s+/, "").split(/\#/)
        hst.each do |x| 
            if x != ''
                sh = Hashtag.new(:name => x, :post_id => @post.id)
                sh.save
            end  
        end
        #render plain: params[:post].inspect
        @post.image.attach(params[:post][:image])
        redirect_to @post
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
        Hashtag.where(post_id: params[:id]).delete_all
        Post.destroy(params[:id])
        redirect_to root_path
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(params.require(:post).permit(:title, :body, :hashtags))
          # Handle a successful update.
          redirect_to @post
        else
          render 'edit'
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        auth = request.env["omniauth.auth"]
        user = User.find_by_uid(auth["uid"]) || User.create_with_omniauth(auth)
        session[:user_id] = user.id
        redirect_to root_url, :notice => "Signed in!"
      end
      
      def destroy
        if current_user
          session.delete(:user_id)
        end
        redirect_to root_url, :notice => "Signed out!"
      end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def users
        @users = User.all
        render template: "pages/users_all"
    end

    def userposts
        user = User.find(params[:id])
        uid = user.uid
        @userAllPosts = Post.where(uid: uid).find_all
        render template: "pages/users_posts"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
  
    <ul class="nav navbar-nav pull-right">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Users', users_path %></li>
      <li><%= link_to 'Hashtags', hashtags_path %></li>
    <% if current_user %>
    <li><span class="signin_as"><%= current_user.name %></span></li>
      <%= image_tag current_user.photo_url, :class => "img-circle" %>
    <li><%= link_to 'Log Out', signout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
  <% end %>   
  </ul> 
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navigation" %>
  <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/hashtags_all.html.erb
<% @hashtags.each do |h| %>
    <h2>#<%= h.name %></h2>
    <%= link_to 'Posts', hashtag_post_path(h.name) %>
    <span class="mini-counter"><%= @hashtags_count[h.name] %></span>
    <hr>
    <% end %>

app/views/pages/hashtags_posts.html.erb
<% @hashtag_posts.each do |h| %>
    <h2><%= h.title %></h2>
    <p><%= image_tag h.image %><br>
    <%= link_to 'Show Post', h %>
    <hr>
<% end %>

app/views/pages/index.html.erb
<h1>Welcome to my blog</h1>

<div class="row">
<div class="col-md-8 blog-main">
<% @posts.each do |post| %>
   <h2><%= link_to post.title, post %></h2>
   <% if post.image != nil %>
    <%= image_tag post.image %>
   <% end %>
   <p><%= post.body %></p>
<% end %>
</div>
</div>

app/views/pages/users_all.html.erb
<% @users.each do |t| %>
    <h2><%= t.name %></h2>
    <p><%= image_tag current_user.photo_url, :class => "img-circle" %>
    <%= link_to 'Posts', user_post_path(t.id) %><span class="mini-counter"><%= Post.where(uid: t.uid).count %></span>
    <hr>
    <% end %>

app/views/pages/users_posts.html.erb
<% @userAllPosts.each do |t| %>
    <h2><%= t.title %></h2>
    <p>Image: <%= image_tag t.image %><br>
    <%= link_to 'Show Post', t %>
    <hr>
    <% end %>

app/views/post/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
        <label>Title :</label>
        <%= f.text_field :title %>
        <label>Message :</label>
        <%= f.text_area :body %>
        <label>Hashtags :</label>
        <%= f.text_area :hashtags %>
        <label>Image :</label>
        <%= image_tag @post.image %>
        <%= f.file_field :image %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/post/new.html.erb
<h1>Create an article</h1>

<%= form_for @post, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <label>Title :</label>
    <%= f.text_field :title %>
    <label>Message :</label>
    <%= f.text_area :body %>
    <label>Hashtags :</label>
    <%= f.text_area :hashtags %>
    <label>Image :</label>
    <%= f.file_field :image %>
    <%= f.submit "Create" %>
  <% end %>

app/views/post/show.html.erb
<h2><%= @post.title %></h2>
<% if @post.image != nil %>
 <%= image_tag @post.image %>
<% end %>
<p><%= @post.body %></p>

<% if current_user %>
    <% if current_user.uid == @post.uid %>       
            <li><%= link_to 'Edit', edit_post_path(@post) %></li>
            <li><%= link_to 'Destroy', post_path(@post),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></li>
    <% end %>
<% end %>
</tr>